### ISSUE TITLE
Adding database manually - db.dat is absent  

### ISSUE THREAD

**Issue by mehulcs** [regulaforensics/DocumentReader-Flutter#1]
I'm trying to include **db.dat** manually in my app following the instructions at [https://docs.regulaforensics.com/flutter/database#adding-database-manually](https://docs.regulaforensics.com/flutter/database#adding-database-manually).

I performed the below steps.

1. Downloaded and moved file to **project/assets/db.dat**
2. Added **db.dat** path in **pubspec.yaml** file
3. Executed **DocumentReader.initializeReader** function, and this function throws below error.

`PlatformException(, Init failed:com.regula.documentreader.api.errors.DocReaderStateException: db.dat is absent, null)`

**Comment by vyakimchik** [comment]
Hello,

The page of the documentation has been updated. Take a look at it and try it out once again: https://docs.regulaforensics.com/flutter/database#adding-database-manually.

**Comment by mehulcs** [comment]
That worked, Thanks a lot.
