### ISSUE TITLE
DocumentReader.showScanner()

### ISSUE THREAD

**Issue by sghaleb1** [regulaforensics/DocumentReader-Flutter#10]
The `DocumentReader.showScanner().then()` doesn't seem to be working, it expects a `Future` but does not execute when the scanner is complete or cancelled.

Packages and versions used: 
```
flutter_document_reader_api: ^5.7.0
flutter_document_reader_core_full: ^5.7.0
```

I am using the example demo given, but I removed the RFID and using OCR only. I cleaned the code to use minimal functions.

The scanner works and gives results after scanning documents, using a controller. 
But it does not give results in that specific Widget. For example, I click scanner button, I scan document, then setState those results to specific state given. But showScanner() always does the same function, since I cannot pass it parameters.

```
DocumentReader.showScanner().then((s) {
  print('SUCCESS!');
}).catchError((Object error) =>
    print((error as PlatformException).message));
```

Nothing prints when I do this, even the `catchError` doesn't print.

NOTE: The documents even suggest you use `.then()` method. https://docs.regulaforensics.com/flutter/show-scanner

Hope you are able to help.

Thank you

**Comment by vyakimchik** [comment]
Hello,

The code snippet in docs has been corrected, thanks! Actually, there are no callbacks in the `showScanner` function.

**Comment by sghaleb1** [comment]
> 
> 
> Hello,
> 
> The code snippet in docs has been corrected, thanks! Actually, there are no callbacks in the `showScanner` function.


Ok, thank you for the clarification. Are there any plans to include callback in the future?

**Comment by vyakimchik** [comment]
No, we are not going to add callbacks as we don't have a sense of it and there is `EventChannel`. To handle events, you need to use the `EventChannel` where you can handle the `DocumentReaderCompletion` actions.

**Comment by sghaleb1** [comment]
Thank you for the support. I'll look up `EventChannel` to fix my problem.
