### ISSUE TITLE
Error during install the flutter_document_reader_api

### ISSUE THREAD

**Issue by AliuDardan** [regulaforensics/DocumentReader-Flutter#13]
Hi

I have issues during installing the Document Reader API

My pubspec.yaml
dependencies:

-   flutter:
-   sdk: flutter
-   flutter_secure_storage: ^5.0.2
-   flutter_face_api: ^3.1.0
-   flutter_document_reader_api: ^6.2.0
-   flutter_document_reader_core_full: ^6.2.0
-   path_provider:

and when I try to install pods I got this error: 
`[!] CocoaPods could not find compatible versions for pod RegulaCommon:
  In Podfile:
    flutter_document_reader_api (from .symlinks/plugins/flutter_document_reader_api/ios) was resolved to 6.2.0, which depends on
      DocumentReader (= 6.2.2422) was resolved to 6.2.2422, which depends on
        RegulaCommon (= 6.2.110)
    flutter_face_api (from .symlinks/plugins/flutter_face_api/ios) was resolved to 3.2.0, which depends on
      FaceSDK (= 3.2.1061) was resolved to 3.2.1061, which depends on
        RegulaCommon (= 6.1.102)`

**Comment by DmitrySmolyakov** [comment]
Hello @AliuDardan, flutter_face_api is incompatible with flutter_document_reader_api 6.2.0. We will update it shortly. You can use the latest beta version of flutter_face_api_beta: ^0.0.55

**Comment by AliuDardan** [comment]
@DmitrySmolyakov even the old version is not working, same errors. 
Can you suggest which versions are compatible?

**Comment by vyakimchik** [comment]
@AliuDardan please try to run the `pod update` command inside the `ios` folder:
```bash
flutter pub get
cd ios
pod update
```

It seems that caches dependencies are used during the build.

The following versions are compatible with each other:
```yaml
dependencies:
  flutter_document_reader_api: ^6.2.0
  flutter_document_reader_core_fullrfid: ^6.2.0
  flutter_face_api_beta: ^0.0.55
```
