### ISSUE TITLE
[BR] convertCase not working on iOS

### ISSUE THREAD

**Issue by kuhnroyal** [regulaforensics/DocumentReader-Flutter#21]
**Before Submitting, be sure to**
- [x] Update to the latest stable version.
- [x] Read and follow the guides described in the [documentation](https://docs.regulaforensics.com?utm_source=github).
- [x] Try to reproduce in our demo project.
- [x] Search for your issue in the existing GitHub issues.

**Bug Description**
Setting `'convertCase': TextProcessing.ocCapital` crashes on iOS but works on Android.

```
-[__NSCFNumber rawValue]: unrecognized selector sent to instance 0x87ea2e5bb3901eab
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber rawValue]: unrecognized selector sent to instance 0x87ea2e5bb3901eab'
*** First throw call stack:
(0x1b8d94cb4 0x1b1e283d0 0x1b8f09ab8 0x1b8dab0e8 0x1b8e11900 0x1021d53e4 0x10218ab34 0x10218906c 0x1c025a320 0x1c025beac 0x1c0263534 0x1c02640a4 0x1c026ecdc 0x218bc5ddc 0x218bc5b7c)
libc++abi: terminating due to uncaught exception of type NSException
* thread #28, queue = 'com.regula.documentreader.corecontext', stop reason = signal SIGABRT
    frame #0: 0x00000001f7d51578 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1f7d51578 <+8>:  b.lo   0x1f7d51598               ; <+40>
    0x1f7d5157c <+12>: pacibsp 
    0x1f7d51580 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1f7d51584 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
```

**Steps To Reproduce**
```dart
      await DocumentReader.setConfig({
        'processParams': {
          'convertCase': TextProcessing.ocCapital,
        }
      });
```

**Expected behavior**
The code above should work on iOS and Android. Or there needs to be clear documentation on how this needs to be set.

**Environment:**
 - Device: iPhone 14 Pro Max
 - OS: iOS 
 - OS version: 16.6

**Comment by vyakimchik** [comment]
Hello,

The issue has been fixed. Please update to the latest version. Thanks!
