### ISSUE TITLE
[BR] Error in JSON response is not always correctly parsed

### ISSUE THREAD

**Issue by kuhnroyal** [regulaforensics/DocumentReader-Flutter#22]
**Before Submitting, be sure to**
- [x] Update to the latest stable version.
- [x] Read and follow the guides described in the [documentation](https://docs.regulaforensics.com?utm_source=github).
- [x] Try to reproduce in our demo project.
- [x] Search for your issue in the existing GitHub issues.

**Bug Description**

When an error on iOS occurs, the JSON response contains keys that are not parsed from the JSON response, resulting in empty error code/message.

**Steps To Reproduce**
1. Set wrong/unavailable processing scenario
2. Try to scan
3. Inspect the response JSON and the parsed error 

```json
{
  "results" : {

  },
  "action" : 4,
  "error" : {
    "localizedDescription" : "Unavailable scenario, please check that your Core type and license support this scenario",
    "code" : 2
  }
}
```

```dart
    final completion = DocumentReaderCompletion.fromJson(json.decode(data))!;

    if (completion.error != null) {
      final message = completion.error!.message; // null
      final errorCode = completion.error!.errorCode; // null
    }
```

**Expected behavior**

```dart
    final completion = DocumentReaderCompletion.fromJson(json.decode(data))!;

    if (completion.error != null) {
      final message = completion.error!.message; // "Unavailable scenario, please check that your Core type and license support this scenario"
      final errorCode = completion.error!.errorCode; // 2
    }
```

**Environment:**
 - Device: iPhone 14 Prox Max
 - OS: iOS, not yet tested on Android
 - OS version: 16.6

**Additional context**
The `code` and `localizedDescription` fields are not parsed here: https://github.com/regulaforensics/DocumentReader-Flutter/blob/master/lib/document_reader.dart#L1552

**Comment by vyakimchik** [comment]
Hi @kuhnroyal! The issue has been fixed. The fix will be available in the next release version. Thank you!

**Comment by kuhnroyal** [comment]
Thanks looking forward to the next release!
