### ISSUE TITLE
Downloading the database when we launch the app 

### ISSUE THREAD

**Issue by CherukuriSiva** [regulaforensics/DocumentReader-Flutter#3]
I am using your example application to test the Regula library.

Currently, I am seeing the status "Downloading database" at the time of launching the app(Only the First time).

When I go through your documentation... I found this

```
The database stores the documents' data. It's mandatory to have db.dat file if type of the document, OCR zone information should be recognized. If MRZ, Barcode recognition, or image cropping are used, there is no need to have the db.dat file.
```

We want to use only the MRZ scanning feature. So we don't need to use the db.dat file right? 
If yes can you provide some steps on how to modify the code provided in the example application
https://github.com/regulaforensics/DocumentReader-Flutter/tree/master/example

**Comment by CherukuriSiva** [comment]
I am seeing here so many packages...

[https://pub.dev/publishers/mobile.regulaforensics.com/packages](https://pub.dev/publishers/mobile.regulaforensics.com/packages)

If I want to use only the MRZ capture feature which one I can use? and also as mentioned above with out using db.bat file
can I implement the MRZ scan feature?

**Comment by vyakimchik** [comment]
Hello,

Exactly.
> We want to use only the MRZ scanning feature. So we don't need to use the db.dat file right?

Change the [Core](https://docs.regulaforensics.com/flutter/core) type in the [.yaml file](https://github.com/regulaforensics/DocumentReader-Flutter/blob/master/example/pubspec.yaml#L16), and you can remove `prepareDatabase` method from the [project](https://github.com/regulaforensics/DocumentReader-Flutter/blob/master/example/lib/main.dart#L129).
> If yes can you provide some steps on how to modify the code provided in the example application

If you are about to process just MRZ, you can choose the following one: https://pub.dev/packages/flutter_document_reader_core_mrz.
> If I want to use only the MRZ capture feature which one I can use? and also as mentioned above with out using db.bat file
> can I implement the MRZ scan feature?
