### ISSUE TITLE
How to set language preference to English

### ISSUE THREAD

**Issue by CherukuriSiva** [regulaforensics/DocumentReader-Flutter#4]
Currently, I am getting OCR values in both English and Arabic. If I want to receive response values only in English, is there a way I can set language preference to English

```
I/flutter (18512): ***********Name******************* Surname and given names
I/flutter (18512): ***********Value******************* Nihaal Cherukuri
I/flutter (18512): ***********Name******************* Surname and given names
I/flutter (18512): ***********Value******************* ىرو ل
```

Because I am saving the data in HashMap using the above key value pairs. Since keys the same for both Arabic and English... second(Arabic) value is overwriting the first value.

**Comment by vyakimchik** [comment]
Hello,

Yes, you can receive values with the desired LCID. Take a look at the following page: https://docs.regulaforensics.com/flutter/results/getting-results#getting-values. E.g.:
`String surnameAndGivenNames = results.getTextFieldValueByType(eVisualFieldType.FT_SURNAME_AND_GIVEN_NAMES, lcid: LCID.LATIN);`
