### ISSUE TITLE
Where to keep both platform(iOS and Android) licenses?

### ISSUE THREAD

**Issue by CherukuriSiva** [regulaforensics/DocumentReader-Flutter#5]
I have generated the license for the android app and kept it under my assets folder
```
project_root/assets/regula.license
```

and now I have generated a license for iOS. But both are having the same name regula.license.

So where to keep my iOS app license.

Note: Both apps using different bundle identifier and package names.

**Comment by vyakimchik** [comment]
Hello,

You can have only one license file where both platforms are specified with the required app IDs.

Place it in the assets folder. Take a look at the following page: https://github.com/regulaforensics/DocumentReader-Flutter#how-to-build-demo-application.
