### ISSUE TITLE
How to get captured image path instead of base 64 string?

### ISSUE THREAD

**Issue by CherukuriSiva** [regulaforensics/DocumentReader-Flutter#6]
Is there a way we can get a captured image path from the results?

        _docImage = Image.memory(Uri.parse("data:image/png;base64," +
                results
                    .getGraphicFieldImageByType(
                        eGraphicFieldType.GF_DOCUMENT_IMAGE)
                    .replaceAll('\n', ''))
            .data
            .contentAsBytes());

We need an image path.

**Comment by vyakimchik** [comment]
Hello,

We don't store any data on devices.
