### ISSUE TITLE
Auto capture both front and back side of the Emirate ID(UAE) like blinkId

### ISSUE THREAD

**Issue by CherukuriSiva** [regulaforensics/DocumentReader-Flutter#7]
If we see the micro blink sample app [https://github.com/BlinkID/blinkid-flutter/tree/master/sample_files](https://github.com/BlinkID/blinkid-flutter/tree/master/sample_files)

the app will capture the front-side of the emirate id and then it will display animation overlay to flip the card and then it will capture the backside of the emirate id.

Do we have a similar feature where our Regula flutter SDK will scan both the front and backside of the EIDs(User doesn't need to press any button to capture) automatically by showing flip the card kind of animation?

**Comment by vyakimchik** [comment]
Hi. Yeah, sure. To process more than one page of a document, you need to enable `multipageProcessing`. Please take a look at the following page: https://docs.regulaforensics.com/flutter/custom-settings#multipage-processing.

**Comment by CherukuriSiva** [comment]
Thank You @vyakimchik for your prompt response. I just checked the app by enabling **### multipageProcessing**. It is working perfectly fine.

However, I have one more query to ask... 

In the image results, we are getting only the backside Image of the EID. How can we get both the front Image and backside of the image? Because we have to save both the images along with the text results.

**Comment by vyakimchik** [comment]
In order to get the appropriate document side, you should use the property `pageIndex`, which is available in [`DocumentReaderGraphicResult`](https://docs.regulaforensics.com/flutter/results/description-of-results#graphic-result) class, e.g. pageIndex = 0 - it’s the first (front) side of the document, pageIndex = 1 - the second (back) side of the document. Build-in methods: https://docs.regulaforensics.com/flutter/results/getting-results#getting-values-1.

**Comment by CherukuriSiva** [comment]
I tried below code snippet to capture both sides of the images

``
      if(results.getGraphicFieldImageByType(eGraphicFieldType.GF_PORTRAIT, source: eRPRM_ResultType.RPRM_RESULT_TYPE_GRAPHICS, pageIndex: 0) != null) {
        _docImage = Image.memory(base64Decode(results.getGraphicFieldImageByType(eGraphicFieldType.GF_PORTRAIT, source: eRPRM_ResultType.RPRM_RESULT_TYPE_GRAPHICS, pageIndex: 0)));
      }

      // Get portrait image from the first page
      if(results.getGraphicFieldImageByType(eGraphicFieldType.GF_PORTRAIT, source: eRPRM_ResultType.RPRM_RESULT_TYPE_GRAPHICS, pageIndex: 1) != null) {
        _docImage2 = Image.memory(base64Decode(results.getGraphicFieldImageByType(eGraphicFieldType.GF_PORTRAIT, source: eRPRM_ResultType.RPRM_RESULT_TYPE_GRAPHICS, pageIndex: 1)));
      }

      if(results.getGraphicFieldImageByType(eGraphicFieldType.GF_PORTRAIT, source: eRPRM_ResultType.RPRM_RESULT_TYPE_RAW_IMAGE, pageIndex: 0) != null) {
        _docImage3 = Image.memory(base64Decode(results.getGraphicFieldImageByType(eGraphicFieldType.GF_PORTRAIT, source: eRPRM_ResultType.RPRM_RESULT_TYPE_RAW_IMAGE, pageIndex: 0)));
      }
      // Get portrait image from the first page
      if(results.getGraphicFieldImageByType(eGraphicFieldType.GF_PORTRAIT, source: eRPRM_ResultType.RPRM_RESULT_TYPE_RAW_IMAGE, pageIndex: 1) != null) {
        _docImage4 = Image.memory(base64Decode(results.getGraphicFieldImageByType(eGraphicFieldType.GF_PORTRAIT, source: eRPRM_ResultType.RPRM_RESULT_TYPE_RAW_IMAGE, pageIndex: 1)));
      }

      if(results.getGraphicFieldImageByType(eGraphicFieldType.GF_DOCUMENT_IMAGE, source: eRPRM_ResultType.RPRM_RESULT_TYPE_RAW_IMAGE, pageIndex: 0) != null) {
        _docImage5 = Image.memory(base64Decode(results.getGraphicFieldImageByType(eGraphicFieldType.GF_DOCUMENT_IMAGE, source: eRPRM_ResultType.RPRM_RESULT_TYPE_RAW_IMAGE, pageIndex: 0)));
      }

      // Get portrait image from the first page
      if(results.getGraphicFieldImageByType(eGraphicFieldType.GF_DOCUMENT_IMAGE, source: eRPRM_ResultType.RPRM_RESULT_TYPE_RAW_IMAGE, pageIndex: 1) != null) {
        _docImage6 = Image.memory(base64Decode(results.getGraphicFieldImageByType(eGraphicFieldType.GF_DOCUMENT_IMAGE, source: eRPRM_ResultType.RPRM_RESULT_TYPE_RAW_IMAGE, pageIndex: 1)));
      }

      if(results.getGraphicFieldImageByType(eGraphicFieldType.GF_DOCUMENT_IMAGE, source: eRPRM_ResultType.RPRM_RESULT_TYPE_GRAPHICS, pageIndex: 0) != null) {
        _docImage7 = Image.memory(base64Decode(results.getGraphicFieldImageByType(eGraphicFieldType.GF_DOCUMENT_IMAGE, source: eRPRM_ResultType.RPRM_RESULT_TYPE_GRAPHICS, pageIndex: 0)));
      }
      // Get portrait image from the first page
      if(results.getGraphicFieldImageByType(eGraphicFieldType.GF_DOCUMENT_IMAGE, source: eRPRM_ResultType.RPRM_RESULT_TYPE_GRAPHICS, pageIndex: 1) != null) {
        _docImage8 = Image.memory(base64Decode(results.getGraphicFieldImageByType(eGraphicFieldType.GF_DOCUMENT_IMAGE, source: eRPRM_ResultType.RPRM_RESULT_TYPE_GRAPHICS, pageIndex: 1)));
      }
``

Still, I'm not able to capture both sides.

``
              children: <Widget>[
                Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      // createImage("Portrait", 150, 150, _portrait.image),
                      createImage("Document image", 150, 200, _docImage.image),
                      createImage("Document image", 150, 200, _docImage2.image),
                    ]),
                Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      // createImage("Portrait", 150, 150, _portrait.image),
                      createImage("Document image", 150, 200, _docImage3.image),
                                            createImage("Document image", 150, 200, _docImage4.image),

                    ]),
                Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      // createImage("Portrait", 150, 150, _portrait.image),
                      createImage("Document image", 150, 200, _docImage5.image),
                                            createImage("Document image", 150, 200, _docImage6.image),

                    ]),
                Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      // createImage("Portrait", 150, 150, _portrait.image),
                      createImage("Document image", 150, 200, _docImage7.image),
                                            createImage("Document image", 150, 200, _docImage8.image),

                    ]),
``

In my UI I am seeing all same types of images.

Sometimes the front side of the Emirate Id getting displayed in all rows or sometimes the back side of the Emirate Id getting displayed in all rows but not together.

**Comment by CherukuriSiva** [comment]
@vyakimchik did you get time to look into it. 

At a time I am only receiving only one side of the image(Either front or backside but not together).

Could you guide me to fix the issue in my code...

**Comment by vyakimchik** [comment]
Hello,

Sorry for keeping you waiting.

The issue has been fixed, and the new version has been published. Please check it out.
