### ISSUE TITLE
Unable to run the app on android

### ISSUE THREAD

**Issue by venky79** [regulaforensics/DocumentReader-Flutter#8]
The plugin `flutter_document_reader_core_fullrfid` doesn't have a main class defined in
C:\Users\admin\Downloads\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_document_reader_core_fullrfid-5.3.0\android\src\main\java\io\flutter\plugin
s\regula\documentreader\flutter_document_reader_core\FlutterDocumentReaderCorePlugin.java or
C:\Users\admin\Downloads\flutter_windows_1.20.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_document_reader_core_fullrfid-5.3.0\android\src\main\kotlin\io\flutter\plug
ins\regula\documentreader\flutter_document_reader_core\FlutterDocumentReaderCorePlugin.kt. This is likely to due to an incorrect `androidPackage:
io.flutter.plugins.regula.documentreader.flutter_document_reader_core` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and
consider using a different plugin in the meanwhile.

I Have Cloned the project from github url (https://github.com/regulaforensics/DocumentReader-Flutter) and trying to run the app on android getting above error please anyone help me

**Comment by vyakimchik** [comment]
Hello,

Thanks for reporting!

Could you please describe steps on how to reproduce this issue?

**Comment by vyakimchik** [comment]
The issue was closed because there hasn't been any activity recently. Feel free to [open a new one](https://github.com/regulaforensics/DocumentReader-Flutter/issues/new) if you still experience this problem.
